package dk.dtu.cdio.ANIMAL.brick;

public enum NavCommand {
	
	TRAVEL, TRAVEL_ARC, ROTATE, ARC, STOP, STOP_AND_CLEAR, CLEAR, SET_TRAVELSPEED, SET_ROTATESPEED, SET_ACCELERATION, POP, LATENCY_TEST;

}
